defmodule NanoGlobalCacheTest do
  use ExUnit.Case
  doctest NanoGlobalCache

  defmodule TokenCache do
    use NanoGlobalCache

    cache :github do
      expires_in 200

      fetch fn ->
        send(Agent.get(:cur_test, & &1), :github)
        {:ok, "gho_#{:rand.uniform(10000)}"}
      end
    end

    cache :google do
      expires_in 200

      fetch fn ->
        send(Agent.get(:cur_test, & &1), :google)
        :error
      end
    end

    # fetch/1 is auto-generated by the transformer
  end

  setup do
    this = self()
    Agent.start_link(fn -> this end, name: :cur_test)
    on_exit(fn -> TokenCache.clear_all() end)
    :ok
  end

  describe "fetch/1" do
    test "caches GitHub tokens until expiration" do
      {:ok, token1} = TokenCache.fetch(:github)
      assert_receive :github

      {:ok, token2} = TokenCache.fetch(:github)
      # cached, no re-execution (no external API call)
      refute_receive :github
      assert token1 == token2

      Process.sleep(300)

      {:ok, token3} = TokenCache.fetch(:github)
      assert_receive :github
      assert token3 != token1
    end

    test "does not cache Google token refresh failures" do
      :error = TokenCache.fetch(:google)
      assert_receive :google

      :error = TokenCache.fetch(:google)
      # refresh failures are retried on each call
      assert_receive :google
    end
  end

  describe "fetch!/1" do
    test "returns GitHub token on success" do
      token = TokenCache.fetch!(:github)
      assert_receive :github
      assert String.starts_with?(token, "gho_")
    end

    test "raises on Google token refresh failure" do
      assert_raise RuntimeError, fn -> TokenCache.fetch!(:google) end
      assert_receive :google
    end
  end

  describe "clear" do
    test "removes cache before expiration" do
      {:ok, token1} = TokenCache.fetch(:github)
      {:ok, token2} = TokenCache.fetch(:github)
      assert token1 == token2

      TokenCache.clear(:github)

      {:ok, token3} = TokenCache.fetch(:github)
      assert token3 != token1
    end

    test "clear_all removes all caches" do
      {:ok, token1} = TokenCache.fetch(:github)
      :error = TokenCache.fetch(:google)

      TokenCache.clear_all()

      {:ok, token2} = TokenCache.fetch(:github)
      assert token2 != token1
    end
  end
end
